### ISSUE TITLE
Installation手順の不足

### ISSUE THREAD

**Issue by demachitse** [skanehira/ghf#1]
## 🐛 Summary
https://github.com/skanehira/ghf/blob/master/README.md#installation
Installation手順の不足があり手順通りだとインストールできない

## 💔 Cause
`cd`のコマンドが足りない

## 👀 Steps
```diff
$ git clone https://github.com/skanehira/ghf.git
$ go install
```
の通りコマンドを実行

## 🆗 Expected
```diff
$ git clone https://github.com/skanehira/ghf.git
+ $ cd ghf
$ go install
```

**Comment by skanehira** [comment]
直しました
ありがとうございます
