### ISSUE TITLE
Windows環境でアップロード時、アップロードのパスがおかしい

### ISSUE THREAD

**Issue by demachitse** [skanehira/ghf#6]
## 🐛 Summary
Windows環境でアップロード時、アップロードのパスがおかしい

## 💔 Cause
Windows環境では [filepath.Join()](https://github.com/skanehira/ghf/blob/a2bff22e12255a7172e0533d8c61e7e23e4d948e/cmd/upload.go#L65) でパスをくっつけた時に、フォルダ区切り文字がバックスラッシュになってしまうが、githubでのフォルダ区切り文字がスラッシュのためと思われる

## 👀 Steps
1. Windows環境で`ghf up`コマンドを使ってファイルをアップロードする
2. 以下の添付画像のように、本来であれば自動でフォルダが切られるはずがファイル名とバックスラッシュでくっついてしまう

![スクリーンショット 2021-02-02 16 25 40](https://user-images.githubusercontent.com/53329513/106566270-71cf7d80-6573-11eb-8bc2-1962e3c0473f.png)

## 🆗 Expected
Windows環境でも動作が変わらない

**Comment by skanehira** [comment]
fixed
